kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: floq-www
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: floq-www
    spec:
      containers:
      - name: floq-www
        image: eu.gcr.io/marine-cycle-97212/floq-www:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: floq-www-ingress
  namespace: default
spec:
  rules:
  - host: www.floq.no
    http:
      paths:
      - backend:
          serviceName: floq-www
          servicePort: 80
        path: /
  - host: floq.no
    http:
      paths:
      - backend:
          serviceName: floq-www
          servicePort: 80
        path: /
  tls:
  - hosts:
    - www.floq.no
    - floq.no
    secretName: floq-www-tls
---
kind: Service
apiVersion: v1
metadata:
  name: floq-www
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: floq-www
